var solars = JSON.parse(localStorage.getItem('solar'));
var ascendentes = JSON.parse(localStorage.getItem('ascendente'));
var insertsol = document.querySelector('div#solarf')
var insertasc = document.querySelector('div#ascf')
var insert_txt_asc = document.querySelector('div#txt_asc')
var insert_txt_sol = document.querySelector('div#txt_sol_asc')

switch (String(solars)) {



    case '1':

        insertsol.innerHTML = '<strong>SIGNO SOLAR</strong><img class="img_signos" id="img_sol" src="img/aquario.svg" />'
        insert_txt_sol.innerHTML = '<h1>SOL EM AQUARIO</h1><h2>SIGNO AQUÁRIO NO AMOR & SEXO</h2><p>O verdadeiro aquariano ama a liberdade e detesta pessoas grudentas e possessivas, ciumentas e que busquem, constantemente, provas de amor. Gosta de amar livremente, sem que peçam nada em troca. Signo ideal para relações fugazes e pouco estáveis. São autónomos, mas podem ser bastante fieis e amar uma pessoa pela vida inteira, desde que assim o decidam.<p>O nativo deste signo não gosta de rotinas nem de coisas muito simples. No sexo, não se sabe bem se é ele quem tem a iniciativa ou quem seduz. Não entende o parceiro, mas está sensível a todas as suas necessidades. O que retira do sexo é bem mais do que o prazer carnal e pessoal. O sexo, para o aquariano, é uma forma de ficar conhecer a pessoa que está do outro lado. Quanto mais os parceiros se envolvem, mais significativa fica a compromisso.<br><br><h2>SIGNO AQUÁRIO NO DINHEIRO & TRABALHO</h2><p>Esse é o signo da tecnologia, estando sempre presente naquilo que é tencologia, inovação e ciência. Gosta de partilhar tudo aquilo que descobre e de colocar as suas descobertas ao serviço de todas as pessoas. É também um signo vocacionado para a política, mas é demasiado revolucionário, apesar de democrata. Profissionalmente, é autoritário, dominador, mental e muito frio. Muitas vezes, para o aquariano, as soluções para os problemas são violentas. Destaca-se na moda, as artes literárias, na política e nos assuntos históricos.</p><br><h2>SIGNO AQUÁRIO NA SAÚDE</h2><p>O ponto mais vulnerável do aquariano é, sem dúvida, o sistema nervoso periférico. Tem um ritmo de vida demasiado agitado e muitas vezes não consegue dominar a sua mente, sendo, por norma, uma pessoa desiquilibrada.</p><br><br>'

        break

    case '2':

        insertsol.innerHTML = '<strong>SIGNO SOLAR</strong><img class="img_signos" id="img_sol" src="img/peixes.svg" />'
        insert_txt_sol.innerHTML = '<h1>SOL EM PEIXES</h1><h2>SIGNO PEIXES NO AMOR & SEXO</h2><p> Esse é o mais romântico signo do zodíaco. Dá a vida por quem ama e sente as dores daqueles que o rodeiam, atingindo uma dimensão sentimental maior do que a própria vida. O pisciano procura sempre a alma gêmea e exige sempre o máximo das suas relações. Tem grande capacidade de se vitimizar, chorando e gritando sempre que é contrariado. Consegue sempre o que quer pois tem grande capacidade de sedução e charme, e não pensa duas vezes antes de usar dessas armas. É romântico, mas é também muito instável e busca sempre o desconhecido — o que pode significar que não é um signo dado ao casamento ou a relações muito sérias. No sexo, está sempre atento às necessidades do outro e muitas vezes esquece as suas próprias necessidades, demonstrando sua insegurança. Aposta fortemente nas preliminares e adora um carinho depois do ato sexual. O sexo, para os piscianos, é uma forma de satisfazer seu parceiro.</p><br><br><h2>SIGNO PEIXES NO DINHEIRO & TRABALHO</h2>  <p> Esse signo faz o que mais ninguém faz. Quer procurar conhecer o desconhecido, quer vender os legumes e frutas que ninguém sabe de onde vem, mas que são uma delícia. É a pessoa certa para trabalhar com magia, com artigos místicos, excelente poeta e cineasta e com atividades que o ajudam a conseguir atingir outra dimensão. Podemos vê-lo também como músico, bailarino, médico, religioso ou escritor. Numa ordem espiritual, é quem toda a gente segue e que busca os mistérios ainda não revelados. </p><br><br><h2>SIGNO PEIXES NA SAÚDE</h2><p>É comum ver o nativo deste signo com problemas relacionados com os pés. É propenso a intoxicações alimentares e é facilmente levado pelos vícios. Costumam ter bastantes problemas relacionados com o sono, mas a acupuntura costuma resolver eles.</p><br><br>'
        break

    case '3':

        insertsol.innerHTML = '<strong>SIGNO SOLAR</strong><img class="img_signos" id="img_sol" src="img/aries.svg" />'
        insert_txt_sol.innerHTML = '<h1>SOL EM ÁRIES</h1><h2>SIGNO DE ÁRIES NO AMOR & SEXO</h2><p> O ariano é muito emotivo e impulsivo no amor. Não gosta de nada que o faça esperar, mas gosta de romantismo e do ato da conquista e pode levar muito tempo para criar o momento certo e especial. Não usa meias palavras e quando quer, segue lutando até conseguir. No amor, ele mostra a sua generosidade e é capaz de ir até no fim do mundo para mostrar aquilo que sente, enfrentando tudo e todos. Mas é também um signo bastante inocente e muitas vezes o desejo e a paixão cega ele. Quando machucado, o ariano entra num profunda depressão e se sente enganado podendo mesmo ficar agressivo. </p> <br> <br> <h2>SIGNO DE ÁRIES NO DINHEIRO & TRABALHO</h2><p> O ariano gosta de profissões que representem risco, que necessitem de liderança e atitude, que permitam controlar o seu tempo e a forma de gerir sua agenda. Como é um signo impulsivo, é fácil perceber que o ariano só pode liderar pois não gosta de ser comandado por outros. O ariano manda, faz e gosta de fazer o mais rápido possível. Tudo o que envolva força, determinação e liderança, é bem vindo para o ariano. É comum vê-lo em profissões como como Jornalista, Juiz, Político e Militar. Mas a sua sensibilidade também lhe permite ser escritor ou artista de uma outra área.  </p><br> <br> <h2> SIGNO DE ÁRIES NA SAÚDE </h2> <p> Esse é o signo da cabeça e do cérebro. Muitas vezes, pela sua impulsividade, não há como regular seu chakra principal e as energias ficam desiquilibradas. Assim, para o ariano as dores de cabeça ou enxaquecas são algo comum e muitas vezes são causadas pelo facto de não conseguir fazer ou ter o que pretende. As febres altas ou doenças do sistema nervoso periférico, por exemplo, são bastante comuns neste signo e isso está também relacionado com o facto de ser um signo de fogo. <br><br> </p>'
        break

    case '4':

        insertsol.innerHTML = '<strong>SIGNO SOLAR</strong><img class="img_signos" id="img_sol" src="img/touro.svg" />'
        insert_txt_sol.innerHTML = '<h1>SOL EM TOURO</h1><h2>SIGNO DE TOURO NO AMOR & SEXO</h2><p> Esse é um dos signos mais sensuais de todo o Horóscopo. No amor, prefere as relações sentimentais às relações só de sexo. Gosta do desafio de ter uma compromisso estável que passa pelo tempo sem grandes altos e baixos, mas nunca esquecendo a sensualidade que tão bem caracteriza os taurinos. Nas amizades, é fiel e tem sempre uma palavra para dizer. Gosta de fazer com que seus amigos se sintam bem, mas não esconde a verdade de nenhum deles. Sua base é a confiança e a fidelidade, procurando sempre cuidar daqueles que mais ama. É uma pessoa forte, mas com emoções. Amante da beleza, do romantismo e do conforto, no fundo, amantes de tudo o que dá prazer. </p> <br><br> <h2> SIGNO TOURO NO DINHEIRO & TRABALHO </h2> <p> Por ser alguém que gosta de realizar, de fazer ele mesmo, se adapta perfeitamente a todas as profissões das artes, sobretudo nas profissões que dedicam à produção propriamente dita ou a manter um sistema. Além disso, são pessoas que gostam de desafios e, portanto, dão-se perfeitamente numa profissão com grande volume de trabalho para fazer. Ao oposto do primeiro signo do zodíaco, Áries, ele não gosta do desconhecido e procura sempre apostar naquilo que é firme e não representa qualquer risco. É muito esforçado e essa determinação faz com que consigam, quase sempre, atingir os seus objetivos. </p> <br> <br> <h2> SIGNO TOURO NA SAÚDE </h2> <p>  Quando se fala em saúde, esse é o signo do zodíaco que refere a garganta e a tiróide e este é o chakra – o da garganta – que trata de toda a energia relativa ao sentimento. Assim, são sensíveis a problemas de voz infeções na garganta e na faringe e dores no pescoço. Apesar de terem muita disciplina, não gostam de praticar exercício físico. Gostam de comer bem, mas têm grande tendência para ganho excessivo de peso porque seu metabolismo é muito lento. </p> '
        break
    case '5':

        insertsol.innerHTML = '<strong>SIGNO SOLAR</strong><img class="img_signos" id="img_sol" src="img/gemeos.svg" />'
        insert_txt_sol.innerHTML = '<h1>SOL EM GÊMEOS</h1><h2>SIGNO DE GÊMEOS NO AMOR & SEXO</h2><p> Para os geminianos, ficar sempre com a mesma pessoa é perda de tempo. Gosta de variar e de conhecer pessoas novas, capazes de fazer seu cérebro se desenvolver, ganhar novos conhecimentos e informações. Este signo do zodíaco procura sempre pessoas que os façam viajar, seja de verdade, seja de forma imaginária. Não é um signo fiel por natureza porque tem na sua essência a necessidade de procurar sempre algo novo. <p> <br><br> <h2> SIGNO GÊMEOS NO DINHEIRO & TRABALHO </h2> <p> Se a profissão tiver grande necessidade de informação, variedade de temas e troca de conhecimento com diversas pessoas, ele ganha de qualquer um do zodíaco. Eles gostam da palavra, e uma das suas características profissionais é a capacidade de convencer alguém com uma boa conversa. Assim, é comum ver um geminiano jornalista ou comerciante extremamente bem preparado. Mas são também comuns tradutores de todas as línguas, filósofos e matemáticos com muito sucesso. </p> <br><br> <h2> SIGNO GÊMEOS NA SAÚDE <h2> <p> É o signo da comunicação, e por isso estão mais suscetíveis de sofrer de problemas de fala. Mas também os pulmões, os braços e mãos podem ser afetados. Como signo de ar que são, são frequentes as doenças respiratórias, sejam elas de que categoria forem. Os meios de comunicação – mãos para tocar e pés para se movimentarem – são também muito afetados pelas doenças no geminiano e, por isso, precisam ter uma atenção redobrada com tudo isso. Quando as trocas não se dão ou não existe informação nova, o nativo deste signo tem também tendência para entrar em estados profundos de tristeza e a meditação pode ajudar a aliviar nessa fase. </p> '
        break

    case '6':

        insertsol.innerHTML = '<strong>SIGNO SOLAR</strong><img class="img_signos" id="img_sol" src="img/cancer.svg" />'
        insert_txt_sol.innerHTML = '<h1>SOL EM CÂNCER </h1><h2>SIGNO DE CÂNCER NO AMOR & SEXO</h2><p> Esse é o signo do romantismo e do sentimento. Gosta de privacidade, de intimidade, de pequenos momentos surpresa passados com quem mais ama. Gosta de sentir prazer com o prazer dos outros e encontra na imaginação muitas formas de surpreender a pessoa amada. Como gosta de manter o que tem, o canceriano consegue ser muito possessivo nas suas relações e é frequente ter demonstrações de carência profundas. Quando é trocado por outros afazeres, tende a ser grudento e não descansa enquanto não for o foco principal. </p> <br><br> <h2>SIGNO CÂNCER NO DINHEIRO & TRABALHO</h2><p> O canceriano costuma fazer carreira em empresas de sociedades familiares e não gosta de competição. Quando se envolve demasiado, por norma, abandona rapidamente o emprego e, portanto, é preciso que encontre um trabalho passivo e onde possa ser elogiado. Como empregado, o canceriano é calmo, paciente e disciplinado. Cumpre seu dever de forma lenta mas eficaz. Como chefe, é demasiado brando com seus empregados e não tem capacidade de liderança. As profissões certas para o canceriano são de antiquário ou arqueólogo, hotelaria e restauração, historiador, marinheiro, poeta, religioso ou veterinário. </p> <br><br> <h2> SIGNO CÂNCER NA SAÚDE </h2> <p> Esse é o signo do zodíaco que rege a parte digestiva do nosso organismo e isso faz com que esteja mais disposto a ter gastrites ou úlceras. Também rege os seios e portanto toda a parte feminina fica afetada e o canceriano poderá ter problemas nas mamas, sofrer com TPM, ter doenças do aparelho reprodutivo e ginecológico e endometriose. Muitas vezes, podem ter problemas psicológicos que se acabam manifestando através de problemas físicos. </p> '
        break

    case '7':

        insertsol.innerHTML = '<strong>SIGNO SOLAR</strong><img class="img_signos" id="img_sol" src="img/leao.svg" />'
        insert_txt_sol.innerHTML = '<h1>SOL EM LEÃO  </h1><h2>SIGNO DE LEÃO NO AMOR & SEXO</h2><p> Esse signo é drama em pessoa, mas muito romântico e sensual. Este é o signo do amor com cortesia, das grandes provas de amor e da romantização de todo os atos. O apaixonado que faz de tudo para agradar quem ama. Gosta de ser o centro das atenções mas também faz da pessoa que ama o centro da sua atenção. É possessivo e detesta rejeição, frieza e descaso. No sexo, o leonino se envolve demais e tudo faz para atingir a seu próprio prazer. Mas a verdade é que não é muito difícil de agradar a um leonino, basta fazer dele o centro de todas as atenções e alimentar a sua vaidade. <p> <br> <br> <h2> SIGNO LEÃO NO DINHEIRO & TRABALHO </h2><p> É um signo que se adapta bem a situações de liderança, desafio e risco. Procura, sempre, atividades que lhe tragam prestígio e nem tanto dinheiro no final do mês. Gosta de explorar e mostrar que consegue ser sempre melhor. É um excelente organizador, mas não é tão bom como executante. Como mestre que é, as atividades relacionadas com a educação são bem-vindas, mas só ensina aquilo que é capaz de praticar e, para o leonino, a educação é vista como uma forma de desenvolver as suas habilidades. Como é enérgico, necessita abraçar desafios com muita atividade. Não costuma deixar uma batalha pelo meio e luta até chegar ao fim. </p> <br><br> <h2>SIGNO LEÃO NA SAÚDE<h2> <p> Esse signo rege o coração e isso faz com que tenham possibilidade de desenvolver problemas cardíacos, como infarto, angina, AVC e outras doenças de coração. Tenha bastante atenção com isso. É também comum desenvolver doenças e dores na coluna. É comum, também, desenvolver afecções nos olhos e é necessário ter cuidado com esses problemas que podem significar incapacidade de ver. Respeite bem sua saúde e tome todos os cuidados necessários. </p><br><br> '
        break

    case '8':

        insertsol.innerHTML = '<strong>SIGNO SOLAR</strong><img class="img_signos" id="img_sol" src="img/virgem.svg" />'
        insert_txt_sol.innerHTML = '<h1>SOL EM VIRGEM </h1><h2>SIGNO DE VIRGEM NO AMOR & SEXO</h2><p> Pouco romântico, mas muito sensual, este é um signo instável nos relacionamentos porque tem grande dificuldade em se manter fiel, buscando sempre conhecer mais e melhor as pessoas. É um signo da razão e isso faz com que o virginiano seja avesso a demonstrar sentimentos de carinho ou amor e normalmente fere quem ama porque gosta de criticar. Necessita sempre de palavras que sirvam para diminuir suas inseguranças e nervos constantes. Falta também perceber que o romantismo é importante para as relações. No sexo, o virginiano procura a perfeição e aplicam o máximo de esforço para atingi-la. As emoções ficam de lado porque quer ser o melhor, e tenta aprender o que e como fazer para ter prazer. </p> <br> <br> <h2> SIGNO VIRGEM NO DINHEIRO & TRABALHO </h2> <p> Profissionalmente, se destaca por ser um trabalhador aplicado, fiel e que dá sempre o melhor de si nas atividades que lhe são atribuídas. É perito em usar as mãos e todos os trabalhos manuais lhe caem bem. Além disso, é também engenhoso. Como tem percepção e grande capacidade de observação, o nativo desse signo se dá bem em atividades de catalogação, e em todos os setores que precisem de paciência e aplicação. Consegue ordenar, organizar e colocar o seu conhecimento a serviço de uma empresa. Teoricamente, é perfeito. Pelas suas habilidades, a medicina – de humanos e animais – são áreas em que habitualmente têm sucesso. </p> <br><br> <h2> SIGNO VIRGEM NA SAÚDE </h2> <p> Na saúde, o intestino delgado é regido por esse signo. Daí que seja comum afeções nesse órgão, podendo desenvolver colites, por exemplo, mas tendo também problemas de vesícula, prisão de vente, dores abdominais, entre outras. É normal, também, sofrer por antecipação e isso faz com que todo o sistema nervoso se altere e dê as caras quando menos se espera. Problemas digestivos são banais nesse nativo. </p> '
        break

    case '9':

        insertsol.innerHTML = '<strong>SIGNO SOLAR</strong><img class="img_signos" id="img_sol" src="img/libra.svg" />'
        insert_txt_sol.innerHTML = '<h1>SOL EM LIBRA  </h1><h2>SIGNO DE LIBRA NO AMOR & SEXO</h2> <p> O libriano, no amor, é luz. Evita a paixão louca e é muito sensível à beleza – especialmente física —, mas sempre busca o equilíbrio. É gentil, calmo e muito sociável e isso faz com que tenha uma vida social muito atarefada. Compartilha tudo com quem escolhe para amar. Gosta de compromisso, igualdade e justiça. No sexo, gosta de compartilhar tudo. São duas pessoas em sintonia para que ambos fiquem satisfeitos. No sexo, com ele, duas pessoas se tornam uma só. Para o libriano, no sexo e no amor, o equilíbrio entre opostos é o essencial, e ele tudo faz para se complementem. Para este signo do zodíaco, o sexo é algo que serve como união simbólica.  </p> <br> <br> <h2> SIGNO LIBRA NO DINHEIRO & TRABALHO </h2> <p> Todas as profissões relacionadas com as artes e as expressões plásticas se adequam a esse signo. Mas todas elas têm que ser executadas sem pressões ou competições, pois o libriano é frágil na hora de se impor. Tem dificuldade em liderar projetos e pessoas pois é demasiado brando. As profissões mais comuns são diplomata, artista, músico e advogado. Aqui, pode ter todo o sucesso. É também um signo que busca constantemente a justiça e a sensibilidade, e isso o ajuda a criar uma vida de harmonia, cercando-se sempre de pessoas que estão de acordo com seus sentimentos e valores. Dará um excelente advogado de causas cooperativas e associativas, nos assuntos de cultura, da família e das relações externas. </p> <br><br> <h2> SIGNO LIBRA NA SAÚDE </h2> <p> Os rins são regidos por esse signo, o principal filtro do organismo. Por isso mesmo, os librianos precisam estar atentos às doenças renais, do aparelho urinário. Devem também ter atenção a problemas vasculares e doenças de pele. As doenças metabólicas atingem bastante esse signo e como os librianos não levam uma alimentação equilibrada, isso faz com que estejam mais aptos a desenvolver diabetes. </p> <br><br>'
        break

    case '10':

        insertsol.innerHTML = '<strong>SIGNO SOLAR</strong><img class="img_signos" id="img_sol" src="img/escorpiao.svg" />'
        insert_txt_sol.innerHTML = '<h1>SOL EM ESCORPIÃO   </h1><h2>SIGNO DE ESCORPIÃO NO AMOR & SEXO</h2><p> A paixão é sempre muita intensa para o escorpiano e a sexualidade é sagrada. Guarda muitos segredos porque tem medo de perder o controle, mas quando uma compromisso está prestes a chegar ao fim, o escorpiano tem a capacidade de dar a volta e dar uma vida nova ao relacionamento. Quanto mais fundo e negro for o negócio, mais facilidade tem o escorpiano de se revisitar e renascer, renovado. No sexo, esse signo é fascinado pela dimensão emocional e é voltado para o erotismo, tudo tendo uma tônica erótica. Os grandes prazeres do sexo são paixão, atração e o desejo. Para o nativo deste signo pode resumir-se tudo a emoções e quanto mais intensas forem, melhor ainda e estas emoções podem ser demasiado sísmicas. Paixão é a palavra que o define. </p> <br> <br> <h2> SIGNO ESCORPIÃO NO DINHEIRO & TRABALHO </h2> <p> Esse signo destaca-se no campo profissional como sendo um pesquisador de excelência, indo em busca de mistérios, da finalidade e das origens. Sai-se bem em cirurgia porque gosta de ver corpos, mas também em sociologia e política porque gosta de fazer o mesmo mas no campo social. A psicologia é também bem vista por este signo porque permite entender o que existe dentro de cada um de nós. Pode também ter um papel ativo na administração estatal porque tem capacidades para gerir recursos de outros para o bem comum, nas finanças se destaca por conseguir esticar a riquea dos outros. </p> <br></br> <h2> SIGNO ESCORPIÃO NA SAÚDE </h2> <p> Esse signo rege toda a parte sexual e isso faz com que os órgãos sexuais e reprodutores sejam vulneráveis. As hemorroidas também são comuns nos nativos desse signo. Como é demasiado controlador, um dos seus pontos fracos na saúde é a prisão de ventre e os problemas relacionados com os ciclos menstruais. Mas o seu poder de regeneração é também muito rápido, graças a ser um signo bastante forte. </p> '

        break

    case '11':

        insertsol.innerHTML = '<strong>SIGNO SOLAR</strong><img class="img_signos" id="img_sol" src="img/sagitario.svg" />'
        insert_txt_sol.innerHTML = '<h1>SOL EM SAGITÁRIO   </h1><h2>SIGNO DE SAGITÁRIO  NO AMOR & SEXO</h2><p> Para os sagitarianos, o importante é explorar e conhecer. Pouco ou nada importa a rotina ou estabilidade nas relações. Quer o mundo livre e isso faz com que saia sempre da rotina e colecione amores, sem ficar com nenhum deles. Por vezes, dependendo da sua carta astrológica, pode ser mais estável mas isso é raro de acontecer. Paixões tórridas, vontade de viver grandes sonhos, sensualidade forte e fidelidade mental, muito mais do que sexual. É difícil seduzir um nativo desse signo, mas é sempre considerado muito atraente. Para ele, sexo é rápido, fugaz e não significa nada. Mas também tem vezes que é o oposto, em que queima. Apaixonam-se, normalmente, por pessoas que não podem ter porque isso é uma autêntica aventura para eles, mas isso pode significar desgostos grandes. </p> <br> <br> <h2> SIGNO SAGITÁRIO NO DINHEIRO & TRABALHO </h2> <p> Profissionalmente, o sagitarianos destaca-se na propaganda porque é um verdadeiro divulgador, na edição, no jornalismo, mas no direito também porque não suporta falta de justiça. Também podem fazer carreira no esporte porque ama o ar livre e isso permite melhorar o seu vigor. Mas as profissões do campo espiritual também lhe caem bem, assim como a educação. </p><br><br> <h2> SIGNO SAGITÁRIO NA SAÚDE <h2> <p> As pernas são o seu foco porque isso lhes permite chegar mais longe. Daí que encontra fragilidades nas coxas, nádegas e quadril. Outro ponto fraco é o fígado, as dores ciáticas e as cãimbras. Comem demais e têm possibilidade de desenvolver colesterol alto e obesidade. </p> '
        break

    case '12':

        insertsol.innerHTML = '<strong>SIGNO SOLAR</strong><img class="img_signos" id="img_sol" src="img/capricornio.svg" />'
        insert_txt_sol.innerHTML = '<h1>SOL EM CAPRICÓRNIO   </h1><h2>SIGNO DE CAPRICÓRNIO  NO AMOR & SEXO</h2> <p> Esse signo é bastante controverso no amor. Bastante sensual, o capricorniano gosta de carinhos, mas não gosta de paixões repentinas. É um signo bastante fiel e dá muito de si aos outros, odiando, assim, perder aquilo que tanto lutou para conquistar. Como demora a se dar aos outros, tem muita facilidade em sair machucado das relações.  No sexo, é bastante racional. Gosta de planejar todo o ato e vê o sexo quase como um trabalho minucioso. Todo o processo sexual deve ser demorado e o prazer deve ser prolongado ao máximo. A não ser que seja de sua vontade, o ato sexual com um capricorniano não será romântico porque este não é um signo dado a grandes carícias ou momentos de amor. Ter uma compromisso sexual com um nativo desse signo significa ter alguém disponível para fazer você morrer de prazer. Para um capricorniano, tudo tem que ser levado a sério. Mesmo o amor e o sexo. </p> <br> <br> <h2> SIGNO CAPRICÓRNIO NO DINHEIRO & TRABALHO</h2><p> Os grandes responsáveis das empresas, os politicos e os mentores de grandes projetos sociais são, normalmente, deste signo. Este nativo procura sempre o topo nas atividades profissionais e gosta de ver o mundo bem çá de cima. Despreza as vaidades, mas gosta de se ver no meio delas. Como é um signo solitário, o capricorniano terá sempre tendência para realizar trabalhos de forma independente, onde possa expor sua grandeza sem que outros tenham acesso a interferir. Socialmente pouco evoluído, as ciências sociais o ajudam a compreender a sociedade e os seus processos e estruturas. A verdade é que um capricorniano será um excelente profissional em qualquer profissão porque busca, constantemente, o topo da carreira, é minucioso e tem muita ambição, mesmo que isso signifique não ter tempo para tudo o resto que a vida lhe pode dar. </p> <br><br> <h2> SIGNO CAPRICÓRNIO NA SAÚDE </h2> <p> Tudo o que simboliza a estrutura está relacionado com o esse signo porque ele próprio está sempre procurando ficar no alto. Assim, é comum o capricorniano sofrer com dores na coluna e nos joelhos. Além disso, pode também ter problemas de saúde associados aos ossos, como por exemplo, artroses. </p> <br><br> '
        break
}

switch (String(ascendentes)) {



    case '1':

        insertasc.innerHTML = '<strong>SEU ASCENDENTE</strong><img class="img_signos" id="img_sol" src="img/aquario.svg" />'
        insert_txt_asc.innerHTML = '<h1>ASCENDENTE EM AQUARIO</h1><p>Quem nasceu com ascendente Aquário adora fazer amigos, pois conhecer pessoas com diferentes histórias é essencial para que se sinta vivo. É curioso por natureza, e a sua vontade de aprender leva-o a situações de aventura. Por vezes é excêntrico e faz coisas das quais os outros se arrepiam só de ouvirem falar. Preza a sua liberdade acima de tudo e por isso evitará uma relação onde o seu companheiro o pressione. Quem o ama deve compreender que você nasceu livre e nada nem ninguém o pode prender. É mais amigo do que amante, e mesmo numa relação amorosa espera do seu companheiro alguém que esteja disposto a partir à aventura consigo. Profissionalmente, prefere atividades que o deixem expandir o seu forte poder criativo, nas quais não haja limites pré definidos. Faz questão de estar informado sobre as novidades que surjam relacionadas com a sua profissão. Gosta de trabalhar em grupo, mas sem que as pessoas que o rodeiam interfiram na sua independência.</p>'
        break

    case '2':

        insertasc.innerHTML = '<strong>SEU ASCENDENTE</strong><img class="img_signos" id="img_sol" src="img/peixes.svg" />'
        insert_txt_asc.innerHTML = '<h1>ASCENDENTE EM PEIXES</h1><p>Na vida pessoal, a pessoa com ascendente em Peixes é sensível, delicada e muito romântica. Tem uma natureza tímida e deixa-se influenciar com muita facilidade. É dócil e tem sempre uma palavra amiga para quem o procura. No entanto, quando tem algum problema sofre muito e calado, pois nem sempre encontra alguém que compreenda a sua natureza tão sensível. Vive num mundo de sonho que pouco tem a ver com o mundo real, e quando sente que não é compreendido é nele que se refugia. Gosta de se sentir protegido num relacionamento e terá tendência para sentir-se atraído por alguém com uma personalidade forte, mas que no entanto respeite o seu mundo interior. Profissionalmente, é muito dedicado ao trabalho, esforça-se por atingir a perfeição em tudo o que faz. Gosta de estar em contato permanente com pessoas, mas evita atividades que exijam muito esforço físico.</p>'
        break

    case '3':

        insertasc.innerHTML = '<strong>SEU ASCENDENTE</strong><img class="img_signos" id="img_sol" src="img/aries.svg" />'
        insert_txt_asc.innerHTML = '<h1>ASCENDENTE EM ARIES</h1><p>A nível pessoal, é uma pessoa que passa facilmente do riso às lágrimas, da serenidade à agitação, da alegria à cólera. É muito sincero nos seus sentimentos e os demostra sempre com franqueza e espontaneidade. Apaixona-se com muita facilidade, pois é um conquistador nato. Tem tendência a colocar a pessoa que ama num pedestal, mas quando o decepcionam sofre profundamente. Profissionalmente, é muito ativo e espontâneo. Diz sempre aquilo que pensa e isso por vezes é mal interpretado pelos que o rodeiam. Por outro lado, é muito alegre, possui uma frescura de alma e de sentimentos que ilumina todos os que estão perto de si. Tem um pensamento rápido, gosta de novidades e mudanças e está sempre em movimento, tendo por isso uma grande capacidade de trabalho. As pessoas com um ascendente em Áries gostam de exercer profissões nas quais a monotonia não exista. A criatividade e a novidade os fascina. </p>'
        break

    case '4':

        insertasc.innerHTML = '<strong>SEU ASCENDENTE</strong><img class="img_signos" id="img_sol" src="img/touro.svg" />'
        insert_txt_asc.innerHTML = '<h1>ASCENDENTE EM TOURO<p>Este ascendente torna a pessoa muito sensível e carinhosa. É um amante intenso, sensual, e muito atencioso. No entanto, o ciúme é uma das suas características vincadas. Deve ter cuidado para não se tornar demasiado possessivo, pois isso pode magoar os que ama. Uma vez que é uma pessoa ambiciosa e com um grande gosto pelas aquisições, fará sempre tudo para poder ter um bom nível de vida. Trabalhará arduamente, se necessário for, para que depois se possa dar ao luxo de comprar uma casa sua e de a decorar com objetos bonitos que satisfaçam o seu gosto pessoal.</p></h1>'
        break
    case '5':

        insertasc.innerHTML = '<strong>SEU ASCENDENTE</strong><img class="img_signos" id="img_sol" src="img/gemeos.svg" />'
        insert_txt_asc.innerHTML = '<h1>ASCENDENTE EM GEMEOS</h1> <p> Quem tem este ascendente é geralmente mais racional do que emocional, ou seja, apaixona-se por alguém com quem possa partilhar ideias e trocar opiniões, ou que seja para si um desafio intelectual, que estimule a sua mente, que o faça pensar. Normalmente não cede aos impulsos dos sentidos, analisa bem as questões e tem constante necessidade de pedir e de dar explicações verbais. Por vezes, gosta mesmo de provocar o seu companheiro e de ficar a observar a forma como este reage. Mais do que amante, é um amigo, sempre disposto a conversar e com uma palavra amiga para dizer. Em termos profissionais é um ótimo comunicador. É muito curioso e gosta de estar sempre actualizado com tudo o que se passa à sua volta. A rotina no trabalho é coisa que lhe desagrada, e por isso tem vontade de mudar de atividade vezes sem conta. A profissão ideal para si deverá ser regida por muito movimento, mudanças constantes, e exigir muita comunicação em todos os sentidos.</p> '
        break

    case '6':

        insertasc.innerHTML = '<strong>SEU ASCENDENTE</strong><img class="img_signos" id="img_sol" src="img/cancer.svg" />'
        insert_txt_asc.innerHTML = '<h1>ASCENDENTE EM CANCER</h1><p>A nível afetivo, a pessoa que nasceu com este ascendente é muito emotiva e sensível ao extremo. O coração comanda a sua vida, e o seu estado emocional decide tudo o resto. Se se sente amado e querido, e está feliz com as suas emoções, tudo correrá bem: o trabalho, a vida social, o relacionamento com os que o rodeiam. Se, por outro lado, alguma coisa o angustia, a tristeza que sente não o deixará pensar em mais nada com lucidez. Para si nada no mundo é mais importante que o seu lar, a terra natal, os amigos de infância e aqueles que ama. Quem não o conhece verdadeiramente, não compreende por vezes as suas reações, que parecem inesperadas. Mas a verdade é simples: o que lhe fala ao coração tem primazia sobre o resto. Profissionalmente, a escolha da sua profissão será certamente influenciada pelo seu lado mais sonhador. Muitas vezes pode constituir sociedades com familiares. Não gosta de se integrar em profissões que exijam muita competição. Normalmente optará por profissões onde a sua atuação seja em grande parte passiva, não gosta de mandar nos outros nem de assumir cargos de responsabilidade. Precisa de desenvolver a auto-confiança, não deverá ter medo de confiar em si próprio!</p>'
        break

    case '7':

        insertasc.innerHTML = '<strong>SEU ASCENDENTE</strong><img class="img_signos" id="img_sol" src="img/leao.svg" />'
        insert_txt_asc.innerHTML = '<h1>ASCENDENTE EM LEAO</h1><p>Quem nasceu com este ascendente é generoso, magnânimo, capaz de grandes gestos, e com um coração do tamanho do Mundo. Protege aqueles que ama e é capaz de tudo por eles. No entanto, exige uma coisa em troca: o reconhecimento, a admiração. Uma pessoa com ascendente Leão faz muito pelos outros, mas espera que os seus feitos sejam reconhecidos e devidamente valorizados. É apaixonado, caloroso e arrebatador quando se apaixona. Põe paixão em tudo o que faz, é extremamente entusiasta e dificilmente passa despercebido. O seu "fogo" interior ilumina tudo à sua volta e deixa em todo o lado a marca da sua presença. No entanto, ai daqueles que entrem em confronto consigo! Um Leão enfurecido não dá descanso ao seu adversário e jamais deixa que o derrotem. Profissionalmente, procurará profissões que lhe tragam prestígio. Sendo muito organizado e profissional, gosta de ser o seu próprio chefe. A profissão que escolher terá obrigatoriamente de ter muita agitação, para que possa expandir toda a sua energia.</p>'
        break

    case '8':

        insertasc.innerHTML = '<strong>SEU ASCENDENTE</strong><img class="img_signos" id="img_sol" src="img/virgem.svg" />'
        insert_txt_asc.innerHTML = '<h1>ASCENDENTE EM VIRGEM</h1><p>Na vida pessoal, a pessoa com ascendente Virgem mostra-se cautelosa, meticulosa, desconfiada até não conhecer bem a pessoa com quem está a lidar. Não cede facilmente aos instintos, racionaliza tudo aquilo que faz e analisa todas as questões cuidadosamente antes de dar qualquer passo. Não gosta de ser surpreendido ou de ter de lidar com qualquer situação com que não contava. Quando se apaixona, aproxima-se cuidadosamente, exprimindo-se delicadamente. Assim que se sinta seguro numa relação, é capaz de ser extremamente afetuoso e atencioso com a pessoa que ama. Tem uma forte habilidade para profissões artesanais ou especializadas. Possui uma aguçada inteligência prática, é muito organizado e gosta de trabalhos que exijam disciplina, análise e pesquisa. A profissão é um aspecto muito importante na sua vida, e se preciso for dedica-se a ela de corpo e alma.</p>'
        break

    case '9':

        insertasc.innerHTML = '<strong>SEU ASCENDENTE</strong><img class="img_signos" id="img_sol" src="img/libra.svg" />'
        insert_txt_asc.innerHTML = '<h1>ASCENDENTE EM LIBRA</h1><p>Na sua vida pessoal e sentimental a pessoa com ascendente em Libra gosta de relações amáveis e harmoniosas com os que o rodeiam. Por ser simpático e ter sempre uma palavra amiga, os outros gostam de falar consigo e muitas vezes procuram-no para desabafar os seus problemas. E a verdade é que você nunca consegue dizer "não" a ninguém, esquecendo-se muitas vezes de si próprio e das suas necessidades. Uma vez que procura sempre manter o equilíbrio, até nas suas relações amorosas procura ser racional e controlar as suas emoções. No entanto, uma vez que o signo de Libra é dominado por Vênus, o planeta do amor e da afetividade, você é uma pessoa romântica e é facilmente conquistado por gestos carinhosos como um jantar à luz de velas ou um passeio agradável. Tenderá a escolher profissões que envolvam o tato, a compreensão e o julgamento. Prefere trabalhar num meio com muitas pessoas, mas não aceita críticas facilmente. Gosta de sentir que as pessoas com quem trabalha apreciam o seu desempenho.</p>'
        break

    case '10':

        insertasc.innerHTML = '<strong>SEU ASCENDENTE</strong><img class="img_signos" id="img_sol" src="img/escorpiao.svg" />'
        insert_txt_asc.innerHTML = '<h1>ASCENDENTE EM ESCORPIAO</h1><p>Quem nasceu com ascendente Escorpião é uma pessoa misteriosa, que os outros normalmente têm dificuldade em compreender. A primeira vista mostra-se frio, reservado, e faz por passar despercebido. No entanto, à medida que as pessoas vão ganhando a sua confiança, vai-se tornando cada vez mais carinhoso, afável, mostrando-se até mesmo extrovertido caso se sinta num ambiente acolhedor. Quando se apaixona é intenso, dominador e possessivo, mas também muito fiel. As relações íntimas para si são não só necessárias como vitais: quando encontra alguém em quem confia o bastante para se entregar, torna-se um amante maravilhoso. O amor pelos filhos é uma das coisas mais importantes na sua vida, e por eles é capaz de tudo. Profissionalmente, apreciará trabalhos que lhe permitam a pesquisa profunda e o poder de chefia. Gosta de profissões que lhes permitam a análise exaustiva e nas quais possam mostrar as suas capacidades. Como funcionários são pessoas muito intuitivas e esforçam-se por realizar todo o trabalho que lhes é pedido, mas gostam de o fazer à sua maneira, dão um toque pessoal. Não gostam de ser incomodados</p>'
        break

    case '11':

        insertasc.innerHTML = '<strong>SEU ASCENDENTE</strong><img class="img_signos" id="img_sol" src="img/sagitario.svg" />'
        insert_txt_asc.innerHTML = '<h1>ASCENDENTE EM SAGITARIO</h1><p>A nível afetivo, é um conquistador nato. Apaixona-se com muita facilidade por alguém, por um projeto, por uma causa, pela própria vida. A sua alegria de viver e vontade de correr mundo fazem-no buscar sempre algo novo, interessa-se por vários assuntos muito diferentes e gosta muito de conhecer pessoas. É um amigo bem disposto, adora sair e se divertir. Nas relações afetivas é impetuoso e envolvente. Quando se apaixona, procura seduzir e rodear o ser amado com mil e uma atenções. No entanto, a fidelidade não é o seu forte, e como precisa de estar sempre a se empenhar em alguma conquista, se uma relação esmorece e cai na rotina poderá interessar-se por outra pessoa. Profissionalmente, prefere as profissões em que possa gozar a sua tão preciosa liberdade. Gosta de expandir os seus conhecimentos livremente sem imposições ou burocracias. Admira trabalhos de solidariedade e de caridade. É muito bom colaborador, gosta de trabalhar em equipe, tem bom senso, mas contudo é um pouco indisciplinado.</p>'
        break

    case '12':

        insertasc.innerHTML = '<strong>SEU ASCENDENTE</strong><img class="img_signos" id="img_sol" src="img/capricornio.svg" />'
        insert_txt_asc.innerHTML = '<h1>ASCENDENTE EM CAPRICORNIO</h1><p>Quem tem ascendente Capricórnio é uma pessoa que não gosta de mostrar facilmente as suas emoções. Prefere passar sempre a imagem de alguém com um tremendo controlo de si próprio, que não cede a impulsos ou desejos. O reconhecimento social é uma das coisas de que mais precisa, e por isso tentará, seja qual for o meio sócio-económico onde nasceu, rodear-se de pessoas influentes e cuja amizade lhe possa ser proveitosa no futuro. Não é que seja uma pessoa fria e calculista, pois quando é amigo de alguém é fiel e dedicado. Numa relação amorosa é muito exigente com o seu companheiro e hesitará em dar o primeiro passo. Leva tempo até se decidir e gosta de ter o que é seu como certo. Profissionalmente, é muito empenhado e, qualquer que seja a profissão que escolher, fará sempre o possível para produzir mais e cada vez melhor. Luta até à exaustão por todos os objetivos que pretende atingir. Gosta de profissões que exijam organização e tenham um método de trabalho pré definido.</p>'
        break
}